name: Build and test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.yml'
      - '**/.gitignore'
      - '**/*.md'
      - '**/*.heif'
      - '**/*.heic'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.yml'
      - '**/.gitignore'
      - '**/*.md'
      - '**/*.heif'
      - '**/*.heic'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Dandraka.HeifConvert/Dandraka.HeifConvert.sln
    - name: Build
      run: dotnet build Dandraka.HeifConvert/Dandraka.HeifConvert.sln --no-restore
    - name: Test
      run: dotnet test Dandraka.HeifConvert/Dandraka.HeifConvert.Tests/Dandraka.HeifConvert.Tests.csproj --no-build --verbosity normal